#!/bin/busybox sh
export PATH=/bin
/bin/busybox --install -s /bin
finish() {
    code=$?
    echo "L4LOAD_TEST_EXIT=$code"
    poweroff -f
}
trap finish EXIT
set -eu
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev
ip link set lo up
uname -a
/test -test.v -test.timeout=90s
