virtual_server 198.18.0.1 8080 {
    delay_loop 1
    lvs_sched rr
    lvs_method TUN
    protocol TCP
    alpha
    real_server 10.0.2.2 8080 {
        weight 1
        inhibit_on_failure
        HTTP_GET {
            url {
                path /health
                status_code 200
            }
            connect_port 9090
            connect_timeout 1
            retry 1
            delay_before_retry 1
        }
    }
    real_server 10.0.3.2 8080 {
        weight 1
        inhibit_on_failure
        HTTP_GET {
            url {
                path /health
                status_code 200
            }
            connect_port 9090
            connect_timeout 1
            retry 1
            delay_before_retry 1
        }
    }
}
virtual_server 198.18.0.1 8080 {
    delay_loop 1
    lvs_sched rr
    lvs_method TUN
    protocol UDP
    alpha
    real_server 10.0.2.2 8080 {
        weight 1
        inhibit_on_failure
        HTTP_GET {
            url {
                path /health
                status_code 200
            }
            connect_port 9090
            connect_timeout 1
            retry 1
            delay_before_retry 1
        }
    }
    real_server 10.0.3.2 8080 {
        weight 1
        inhibit_on_failure
        HTTP_GET {
            url {
                path /health
                status_code 200
            }
            connect_port 9090
            connect_timeout 1
            retry 1
            delay_before_retry 1
        }
    }
}
